<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-SLURSDT2" failures="0" tests="6" name="com.xinhu.customertest.test.CaoZuo_test" time="90.747" errors="1" timestamp="07 12æœˆ 2018 00:23:52 GMT" skipped="0">
  <testcase classname="com.xinhu.customertest.test.CaoZuo_test" name="delete" time="9.835"/>
  <testcase classname="com.xinhu.customertest.test.CaoZuo_test" name="addReminSetting" time="35.415"/>
  <testcase classname="com.xinhu.customertest.test.CaoZuo_test" name="star" time="3.263">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.webtest.core.WebDriverEngine.getText(Unknown Source)
at com.xinhu.customertest.test.CaoZuo_test.star(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
    </error>
  </testcase> <!-- star -->
  <testcase classname="com.xinhu.customertest.test.CaoZuo_test" name="addReminSetting" time="29.333"/>
  <testcase classname="com.xinhu.customertest.test.CaoZuo_test" name="detil" time="9.599"/>
  <testcase classname="com.xinhu.customertest.test.CaoZuo_test" name="share" time="3.302"/>
</testsuite> <!-- com.xinhu.customertest.test.CaoZuo_test -->
